title: Instructd
description: Online intake and client portals for UK law firms
url: "https://instructd.co.uk"
baseurl: ""
permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Instructd

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
